name: Knowledge graph workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step clones your repository

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Create necessary directories
      run: |
        mkdir -p graph_test model_test node_data_test embeddings_test

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies listed in your requirements.txt

    - name: Testing script
      env: 
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python3 -W ignore -m unittest testing.py

